//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meander.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meander.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Signal Track.
        /// </summary>
        public static string AddSignalTrack {
            get {
                return ResourceManager.GetString("AddSignalTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meander.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Track.
        /// </summary>
        public static string EditSignalTrack {
            get {
                return ResourceManager.GetString("EditSignalTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meander.
        /// </summary>
        public static string Meander {
            get {
                return ResourceManager.GetString("Meander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Track.
        /// </summary>
        public static string NewSignalTrack {
            get {
                return ResourceManager.GetString("NewSignalTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Track Selected.
        /// </summary>
        public static string NoTrackSelected {
            get {
                return ResourceManager.GetString("NoTrackSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Track.
        /// </summary>
        public static string PickATrack {
            get {
                return ResourceManager.GetString("PickATrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples Count.
        /// </summary>
        public static string SamplesCount {
            get {
                return ResourceManager.GetString("SamplesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Project.
        /// </summary>
        public static string SetupProject {
            get {
                return ResourceManager.GetString("SetupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Kind.
        /// </summary>
        public static string SignalKind {
            get {
                return ResourceManager.GetString("SignalKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Level #{0}.
        /// </summary>
        public static string StepLevelFormat {
            get {
                return ResourceManager.GetString("StepLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Color.
        /// </summary>
        public static string TrackColor {
            get {
                return ResourceManager.GetString("TrackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Name.
        /// </summary>
        public static string TrackName {
            get {
                return ResourceManager.GetString("TrackName", resourceCulture);
            }
        }
    }
}
